id: I492A293B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:36:45+00:00'
last_modified: '2022-06-08T05:45:26.609665+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01635
  title: རིས་མེད་ཆོས་ཀྱི་འབྱུང་གནས་མདོ་ཙམ་སྨོས་པ་བློ་གསལ་མགྲིན་པའི་མཛེས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    21F1:
      image_group_id: I00KG02929
      title: ''
      total_pages: 34
      order: 1
      base_file: 21F1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
