id: P006630
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG01635
  title: རིས་མེད་ཆོས་ཀྱི་འབྱུང་གནས་མདོ་ཙམ་སྨོས་པ་བློ་གསལ་མགྲིན་པའི་མཛེས་རྒྱན
  author: ''
  volumes:
    e2592bb24e4d43479bc4325894e8f802:
      image_group_id: I00KG02929
      title: ''
      volume_number: 1
      total_pages: 34
      base_file: v001.txt
